language: ruby
install: bundle install --jobs=3 --retry=3 --no-deployment
script:
- bundle exec rake assets:precompile
- bundle exec rspec spec/features/
deploy:
  provider: heroku
  api_key:
    secure: WUiFdccJVdR3kJ4+s24xfezASvNTB7Co9Lcrg4gL/lEBXyJKnPApFsk9oR9e3Hn9VsfVJddv6I85auNGKaoqSBjf5GQToj7giBYfFMNktQkgWagXaV4ZVLaOgfCau0PdWBtmN2FCn67aTz1+RcEHXrgz++R72BtRqoE2s6WRlU4=
  on:
    branch: master
  app: railsguides-jp
notifications:
  webhooks:
    secure: HFPm4OWPWKheXFkRLZIlJckLEjZ8eW9a5o/dEZoeKQFjrK2kGrBDft4Xp6aKuqJmv4g/VoDDG5x9ZwTDNAxT4u4q2YbXikkmIFbLsc7cQz4hywXRbkWOTKZHaIdorLF0eZnxPybEVZCflH7LopyobwrBo/KC9SLnn7IUnalCwvg=
env:
  global:
    secure: XaRnC33Blzfr2Qy+IIcA746ZyXg+fgT9ov6XZu0zNXwlYch/GAt0Ixw1ywMXvq4oH5xCHnGCvtJ29EUhTWg3fKnowHXbCTmrUj/F8jsMQCLly7+M9oDW9kRY/oa2iSTUgG3DeGq4IxBcMB2osOBTUWFF1aXkHzvxsKT3QT8KZZo=
