#Headless browser option
browser:
  phantomjs: "phantomjs"
  # slimerjs: "slimerjs"

#If you want to have multiple snapping files, set the file name here
snap_file: "configs/snap.js"

# Type the name of the directory that shots will be stored in
directory: 'shots'

# Add only 2 domains, key will act as a label
domains:
  new: "http://localhost:9292"
  old: "http://localhost:9293"

#Type screen widths below, here are a couple of examples
screen_widths:
  - 1280

#Type page URL paths below, here are a couple of examples
paths:
  2_2_release_notes: /2_2_release_notes.html
  2_3_release_notes: /2_3_release_notes.html
  3_0_release_notes: /3_0_release_notes.html
  3_1_release_notes: /3_1_release_notes.html
  3_2_release_notes: /3_2_release_notes.html
  4_0_release_notes: /4_0_release_notes.html
  4_1_release_notes: /4_1_release_notes.html
  4_2_release_notes: /4_2_release_notes.html
  _license: /_license.html
  _welcome: /_welcome.html
  action_controller_overview: /action_controller_overview.html
  action_mailer_basics: /action_mailer_basics.html
  action_view_overview: /action_view_overview.html
  active_job_basics: /active_job_basics.html
  active_model_basics: /active_model_basics.html
  active_record_basics: /active_record_basics.html
  active_record_callbacks: /active_record_callbacks.html
  active_record_migrations: /active_record_migrations.html
  active_record_querying: /active_record_querying.html
  active_record_validations: /active_record_validations.html
  active_support_core_extensions: /active_support_core_extensions.html
  active_support_instrumentation: /active_support_instrumentation.html
  api_documentation_guidelines: /api_documentation_guidelines.html
  asset_pipeline: /asset_pipeline.html
  association_basics: /association_basics.html
  browserconfig.xml: /browserconfig.xml
  caching_with_rails: /caching_with_rails.html
  command_line: /command_line.html
  configuring: /configuring.html
  constant_autoloading_and_reloading: /constant_autoloading_and_reloading.html
  contributing_to_ruby_on_rails: /contributing_to_ruby_on_rails.html
  credits: /credits.html
  debugging_rails_applications: /debugging_rails_applications.html
  development_dependencies_install: /development_dependencies_install.html
  engines: /engines.html
  favicon.ico: /favicon.ico
  form_helpers: /form_helpers.html
  generators: /generators.html
  getting_started: /getting_started.html
  i18n: /i18n.html
  images: /images
  index: /index.html
  initialization: /initialization.html
  javascripts: /javascripts
  layout: /layout.html
  layouts_and_rendering: /layouts_and_rendering.html
  maintenance_policy: /maintenance_policy.html
  migrations: /migrations.html
  nested_model_forms: /nested_model_forms.html
  options: /options.html
  plugins: /plugins.html
  rails_application_templates: /rails_application_templates.html
  rails_on_rack: /rails_on_rack.html
  routing: /routing.html
  ruby_on_rails_guides_guidelines: /ruby_on_rails_guides_guidelines.html
  security: /security.html
  stylesheets: /stylesheets
  testing: /testing.html
  upgrading_ruby_on_rails: /upgrading_ruby_on_rails.html
  working_with_javascript_in_rails: /working_with_javascript_in_rails.html

#Amount of fuzz ImageMagick will use
fuzz: '20%'

#Set the number of days to keep the site spider file
spider_days:
  - 10

#Choose how results are displayed, by default alphanumeric. Different screen widths are always grouped.
#alphanumeric - all paths (with, and without, a difference) are shown, sorted by path
#diffs_first - all paths (with, and without, a difference) are shown, sorted by difference size (largest first)
#diffs_only - only paths with a difference are shown, sorted by difference size (largest first)
mode: diffs_first

threshold: 5
